const views = [
	{	
		"_id": 1,
		"name": 'Accessories',
		"image": '/views/Accessories.webp',
		"accessories" : [
			{
			   "_id": 1,
			   "name": 'Tulle Monogram Dress',
			   "image": '/images/female_img_3.jpg',
			   "img":'/images/female_img_32.jpg',
			   "imag": '/images/female_img_33.jpg',
			   "description":
				   'This lightweight coat has as fresh utility feel in organic silk toile detailed with color-blocked functional details. The long silhouette is cinched at the waist with an internal drawstring, while pockets on the chest, waist and sleeve emphasize the cargo style. A contemporary layered Peter Pan collar completes the look with a sophisticated finish.',
			   "brand": 'Louis Vuitton',
			   "category": 'Women Fashion',
			   "price": '2,80,000.00'	,
			   "countInStock": 22,
			   "rating": 2.6,
			   "numReviews": 4,
		   },
		   {
			   "_id": 2,
			   "name": 'Speedy P9 Bandoulière 50',
			   "image": '/images/male_img_4.jpg',
			   "img":'/images/male_img_42.jpg',
			   "imag": '/images/male_img_43.jpg',
			   "description":
				   'Creative Director Pharrell Williams revisits the iconic Speedy P9 Bandoulière 50 Monogram Leather bag in luxuriously soft and supple calfskin with the classic Monogram pattern. The Monogram is printed on the Speedy using a sophisticated silk-screen technique that reproduces the twill aspect of the Monogram on canvas, a blurry, almost hand-painted effect.',
			   "brand": 'Louis Vuitton ',
			   "category": 'Men Fashion',
			   "price": '1,04,000.00',
			   "countInStock": 42,
			   "rating": 4.6,
			   "numReviews": 2,
		   },
		   {
			   "_id": 3,
			   "name": 'Leather Cafe Racer',
			   "image": '/images/male_img_2.jpg',
			   "img":'/images/male_img_22.jpg',
			   "imag": '/images/male_img_23.jpg',
			   "description":
				   'This springtime look emanates casual chic. The refined café racer jacket in elegant sand tones is layered over a colorful shirt featuring the Speakerman from the SS23 show. Technical cargo shorts made from a lightweight LV ripstop complete this ensemble.',
			   "brand": 'Louis Vuitton',
			   "category": 'Men Fashion',
			   "price": '1,34,000.00',
			   "countInStock": 18,
			   "rating": 4.5,
			   "numReviews": 2,
		   },
		   {
			   "_id": 4,
			   "name": 'Mikado Playsuit',
			   "image": '/images/female_img_1.jpg',
			   "img":'/images/female_img_12.jpg',
			   "imag": '/images/female_img_13.jpg',
			   "description":
				   'This chic style plays with structure and texture for a contemporary look. The padded lambskin jacket twists the sporty shape of a bomber with the coziness of a puffer, while the playsuit has a dressy, tailored look in elegant wool-silk mikado with a rich, refined finish. A Twist Lock XL handbag introduces a sharp signature',
			   "brand": 'Louis Vuitton',
			   "category": 'Women Fashion',
			   "price": '3,80,000.00',
			   "countInStock": 8,
			   "rating": 4.8,
			   "numReviews": 12,
		   },
		   {
			   "_id": 5,
			   "name": 'Insert Knit Dress',
			   "image": '/images/female_img_2.jpg',
			   "img":'/images/female_img_222.jpg',
			   "imag": '/images/female_img_2333.jpg',
			   "description":
				   'This sporty dress is cut in a casual straight-cut silhouette from a double-sided wool-cashmere blend, which is spun in a textured knit on the outside and a soft brushed finish on the inside. A sheer tulle insert introduces a daring trompe l’oeil deep-V neckline effect to the chest, while an LV anchor patch signs the hemline.',
			   "brand": 'Louis Vuitton',
			   "category": 'Women Fashion',
			   "price": '3,25,000.00',
			   "countInStock": 6,
			   "rating": 4.9,
			   "numReviews": 8,
		   },
		   {
			   "_id": 6,
			   "name": 'Juventus suit',
			   "image": '/images/male_img_1.jpg',
			   "img":'/images/male_img_13.jpg',
			   "imag": '/images/male_img_12.jpg',
			   "description":
				   'This impeccably crafted suit, designed in a Shelton style, boasts a sophisticated allure with its fully lined interior and single vent. Tailored features convenient side adjusters for a personalized fit, offering a sleek silhouette, this exquisite ensemble exemplifies quality and refinement. Originating from Italy, each detail reflects the expertise and craftsmanship of its heritage.',
			   "brand": 'Tom Ford',
			   "category": 'Men Fashion',
			   "price": '2,46,000.00',
			   "countInStock": 21,
			   "rating": 4.1,
			   "numReviews": 3,
		   },
		   {
			   "_id": 7,
			   "name": 'Silk Blend Embroidered Blouson',
			   "image": '/images/male_img_3.jpg',
			   "img":'/images/male_img_32.jpg',
			   "imag": '/images/male_img_33.jpg',
			   "description":
				   'This elegant blouson is given a modern twist with a kimono-inspired collar, while the silk blend fabric features a delicate Monogram Aquagarden motif in watery blue tones. Inspired by a plunge in the sea, this piece is elevated with velvety flocked details and subtly sparkling sequins that make it perfect for dressing up on summer evenings.',
			   "brand": 'Louis Vuitton',
			   "category": 'Men Fashion',
			   "price": '2,39,900.00',
			   "countInStock": 25,
			   "rating": 3.4,
			   "numReviews": 3,
		   },
		   {
			   "_id": 8,
			   "name": 'Animal Sequin T-Shirt Dress',
			   "image": '/images/female_img_4.jpg',
			   "img":'/images/female_img_43.jpg',
			   "imag": '/images/female_img_42.jpg',
			   "description":
				   'A casual silhouette elevated with a rich seasonal signature: This dress makes a shimmering statement thanks to intricate allover sequin embroidery in an abstract animal motif. Crafted in a classic straight-cut T-shirt shape, the fit is ample for comfortable, versatile styling. Complete with a discreet invisible zipper at the back.',
			   "brand": 'Louis Vuitton',
			   "category": 'Women Fashion',
			   "price": '5,90,000.00',
			   "countInStock": 42,
			   "rating": 4.2,
			   "numReviews": 5,
		   },
		   {
			   "_id": 9,
			   "name": 'Patchworked Portrait Leather Jacket',
			   "image": '/images/sample.jpg',
			   "img":'/images/sample2.jpg',
			   "imag": '/images/sample3.jpg',
			   "description":
				   'This Made to Order leather and suede overshirt from the FW23 Show runway features a complex assembly of five different Monogram-embossed types of leather. Cut and assembled by hand, they create a patchworked portrait with a camouflage effect. This exceptional piece, which is lined and lightly quilted, brings a graphic twist to timeless looks.',
			   "brand": 'Louis Vuitton ',
			   "category": 'Men Fashion',
			   "price": '14,66,877.77',
			   "countInStock": 0,
			   "rating": 36,
			   "numReviews": 2,
		   },
	   ],
		
	},
    
];

export default views;
